import = ["~/.config/alacritty/moonfly.toml"]

[env]
TERM = "xterm-256color"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window]
startup_mode = "Maximized"
dynamic_title = false
decorations = "None"
decorations_theme_variant = "Dark"

[font]
size = 8.7
normal = { family = "FiraCode Nerd Font", style = "Medium" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
